# Generated by Django 5.2.5 on 2025-08-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Содержание")),
                ("image", models.ImageField(upload_to="images/", verbose_name="Изображение")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("is_published", models.BooleanField(default=False, verbose_name="Признак публикации")),
                ("count_views", models.SmallIntegerField(default=0, verbose_name="Количество просмотров")),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
            },
        ),
    ]
