# Generated by Django 5.2.5 on 2025-08-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="catagory",
            new_name="category",
        ),
    ]
