# Generated by Django 5.2.5 on 2025-08-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_rename_catagory_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country", models.CharField(max_length=150, verbose_name="Страна")),
                ("itn", models.CharField(max_length=150, verbose_name="ИНН")),
                ("address", models.CharField(max_length=150, verbose_name="Адрес")),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
    ]
