# Generated by Django 5.2.6 on 2025-09-06 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_ut",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
        ),
    ]
